version: "3"

services:
        cs-db:
                build: ./Scripts/
        cs-core-micro:
                build: ./CSCore/
                restart: always
                environment:
                        CONNECTION_DB: Host=cs-db;Database=postgres;Username=postgres
        equipments-diagnostics-micro:
                build: ./CSEAD/
                restart: always
                environment:
                        CONNECTION_DB: Host=cs-db;Database=postgres;Username=postgres
        diag-adsl-micro:
                build: ./CSDiagADSL/
                restart: always
                environment:
                        CONNECTION_DB: Host=cs-db;Database=postgres;Username=postgres
        conf-iptv-micro:
                build: ./CSConfIPTV/
                restart: always
                environment:
                        CONNECTION_DB: Host=cs-db;Database=postgres;Username=postgres
        cs-scheduler-micro:
                build: ./CSScheduler/
                restart: always
                environment:
                        CONNECTION_DB: Host=cs-db;Database=scheduler_db;Username=postgres
                ports:
                        - 8000:80
