version: "3"

services:
        cs-db:
                build: ./Scripts/
        cs-core-micro:
                build: ./CSCore/
                restart: always
                environment:
                        CONNECTION_DB: Host=cs-db;Database=postgres;Username=postgres
                ports:
                        - 8080:80
        cs-scheduler-micro:
                build: ./CSScheduler/
                restart: always
                environment:
                        CONNECTION_DB: Host=cs-db;Database=scheduler_db;Username=postgres
                ports:
                        - 8000:80
